sqlite:
  db_dir: "~/Bureau/perso/ppc/db"
  table_name: null


postgresql:
  table_name: "synced_data"

sync:
  interval: 15
  initial_retry_delay: 1
  max_retry_delay: 60
  connect_timeout: 10

paths:
  timestamp_file: "synchronizer/data/lastSuccessFullTime.json"