services:
  dbsync:
    image: dbsync:latest
    container_name: dbsync
    
    volumes:
      - ./config.yaml:/etc/config.yaml:ro
      - ./.env:/app/.env:ro
      - ./timestamp:/etc/timestamp
      - ~/Bureau/perso/ppc/db:/etc/data/sqlite:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py", "--config_path", "/etc/config.yaml"]
    network_mode: host


