services:
  db-sync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: DBsync
    restart: always
    volumes:
      - ../config.yaml:/app/config.yaml:ro
      - ../.env:/app/.env:ro
      - ../timestamp:/app/timestamp
      - ~/Bureau/perso/ppc/db:/app/data/sqlite:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py"]


